# Disable Swagger and DataSource autoconfigurations
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,springfox.documentation.swagger2.configuration.Swagger2DocumentationConfiguration,springfox.documentation.swagger.web.SwaggerUiWebMvcConfiguration
